//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIONS
    {
        public int IDACTION { get; set; }
        public Nullable<int> IDMODULE { get; set; }
        public string ACTION { get; set; }
        public string HASHUSER { get; set; }
        public string HASHOBJET { get; set; }
        public string HASHGEST { get; set; }
        public string MASTERKEY { get; set; }
    }
}
