//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFFAIRES_FICHIERS
    {
        public System.Guid ID { get; set; }
        public string IDAFFAIRE { get; set; }
        public Nullable<System.DateTime> DATE_CREATION { get; set; }
        public string NOMFICHIER { get; set; }
        public string ORIGINALNAME { get; set; }
        public Nullable<System.Guid> CATEGORIE { get; set; }
        public string COMMENTAIRE { get; set; }
        public Nullable<bool> SUPPRIME { get; set; }
        public Nullable<System.DateTime> DATE_SUPPRESSION { get; set; }
        public string HASHUSERSUPP { get; set; }
    }
}
