//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFFAIRES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AFFAIRES()
        {
            this.AFFAIRES_OBJETS = new HashSet<AFFAIRES_OBJETS>();
            this.FICHIERS = new HashSet<FICHIERS>();
        }
    
        public int idaffaire { get; set; }
        public string INTITULE { get; set; }
        public string HASHAFFAIRE { get; set; }
        public Nullable<int> TYPE_AFFAIRE { get; set; }
        public string DATE_CREATION { get; set; }
        public string DATE_FIN { get; set; }
        public string DATE_FIN_ABO { get; set; }
        public Nullable<int> ID_MASTER { get; set; }
        public string REFERENCE { get; set; }
        public Nullable<bool> ACCES { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string EXTLINK { get; set; }
        public Nullable<int> TYPE_IDENT { get; set; }
        public Nullable<int> LECTURE { get; set; }
        public string ADRESSE { get; set; }
        public string COMPLEMENT { get; set; }
        public string BP { get; set; }
        public string CP { get; set; }
        public string VILLE { get; set; }
        public string PAYS { get; set; }
        public string TELEPHONE1 { get; set; }
        public string TELEPHONE2 { get; set; }
        public string FAX { get; set; }
        public string COMMENTAIRE { get; set; }
        public Nullable<int> IDPROPRIETAIRE { get; set; }
        public string HASHPROPRIETAIRE { get; set; }
        public Nullable<bool> ACTIF { get; set; }
        public Nullable<int> TYPE_SECURITE { get; set; }
        public string HASHMODELE_SEC { get; set; }
        public string DATE_MAJ { get; set; }
        public string NOM_MAJ { get; set; }
        public Nullable<bool> CORBEILLE { get; set; }
        public Nullable<System.DateTime> DATE_SUPPRESSION { get; set; }
        public Nullable<System.DateTime> DATE_PREV_SUP { get; set; }
        public Nullable<System.DateTime> DATE_ARCHIVAGE { get; set; }
        public Nullable<System.DateTime> DATE_PREV_ARCHIVAGE { get; set; }
        public Nullable<bool> PRIVATE { get; set; }
        public Nullable<bool> FIRST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AFFAIRES_OBJETS> AFFAIRES_OBJETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHIERS> FICHIERS { get; set; }
    }
}
