//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class APERCU
    {
        public int IDAPERCU { get; set; }
        public string HASHAPERCU { get; set; }
        public string DOSSIER { get; set; }
        public string DOCUMENT { get; set; }
        public string FULLPATH { get; set; }
    }
}
