//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLES
    {
        public System.Guid id { get; set; }
        public string code { get; set; }
        public Nullable<System.Guid> famille { get; set; }
        public Nullable<System.Guid> ssfamille { get; set; }
        public string designation_longue { get; set; }
        public string designation_courte { get; set; }
        public Nullable<decimal> prix_tarif_ht { get; set; }
        public Nullable<decimal> prix_remise_ht { get; set; }
        public Nullable<decimal> prix_achat_ht { get; set; }
        public Nullable<decimal> coef_vente { get; set; }
        public Nullable<decimal> marge_pourcent { get; set; }
        public Nullable<decimal> taxe_1 { get; set; }
        public Nullable<decimal> taxe_2 { get; set; }
        public Nullable<decimal> taxe_3 { get; set; }
        public Nullable<decimal> poids { get; set; }
        public string dimensions { get; set; }
        public string capacite { get; set; }
        public string masterkey { get; set; }
    }
}
