//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACKOFFICE_GEST
    {
        public int IDBACKOFFICE_GEST { get; set; }
        public Nullable<int> ID_GEST { get; set; }
        public Nullable<int> ID_USER { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
