//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAD_SUBSCRIBE
    {
        public int ID_BAD_SUBSCRIBE { get; set; }
        public string HASHSUBSCRIBE { get; set; }
        public string HASHBAD { get; set; }
        public string HASHOBJETCORRES { get; set; }
        public Nullable<System.DateTime> DATE_ENVOI { get; set; }
        public Nullable<bool> VALIDEE { get; set; }
        public Nullable<bool> NEWBAD { get; set; }
        public Nullable<int> IDDOSSIER { get; set; }
    }
}
