//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAD_LIENS
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> LIENBAD { get; set; }
        public string DESTEMAIL { get; set; }
        public string USERKEY { get; set; }
        public Nullable<System.DateTime> DATEDEBUT { get; set; }
        public Nullable<System.DateTime> DATEFIN { get; set; }
        public Nullable<int> DROITS { get; set; }
    }
}
