//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAD_SUBFOLDER
    {
        public int IDSUBFOLDER { get; set; }
        public string HASHBAD { get; set; }
        public string NOM_DOSSIER { get; set; }
        public Nullable<int> DEPTH { get; set; }
        public string CHEMIN { get; set; }
        public string HASHCREATEUR { get; set; }
        public Nullable<int> PARENT_TYPE { get; set; }
        public Nullable<bool> CORBEILLE { get; set; }
        public Nullable<System.DateTime> DATE_SUPPRESSION { get; set; }
        public Nullable<System.DateTime> DATE_ARCHIVAGE { get; set; }
        public Nullable<System.Guid> HASHOBJET { get; set; }
        public Nullable<bool> ARCHIVE { get; set; }
    }
}
