//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAD_DROITS_GROUPES
    {
        public int ID { get; set; }
        public string HASHBAD { get; set; }
        public Nullable<int> G1 { get; set; }
        public Nullable<int> G2 { get; set; }
        public Nullable<int> G3 { get; set; }
        public Nullable<int> G4 { get; set; }
        public Nullable<int> G5 { get; set; }
        public Nullable<int> G6 { get; set; }
    }
}
