//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAD_DOSSIERS
    {
        public int IDBAD { get; set; }
        public string HASHBAD { get; set; }
        public string HASHPROPRIETAIRE { get; set; }
        public Nullable<System.DateTime> DATE_CREATION { get; set; }
        public string HASHOBJETREP { get; set; }
        public string HASHAFFAIRE { get; set; }
    }
}
