//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAD_AVANCEE
    {
        public int IDBAD { get; set; }
        public string INTITULE { get; set; }
        public string MASTERKEY { get; set; }
        public Nullable<System.DateTime> DATE_CREATION { get; set; }
        public string HASHKEY { get; set; }
        public Nullable<bool> CORBEILLE { get; set; }
        public Nullable<System.DateTime> DATE_ARCHIVAGE { get; set; }
        public string HASHOBJET { get; set; }
        public string NOTIFYTO { get; set; }
        public Nullable<int> DROITS { get; set; }
    }
}
