//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAD_ACCES
    {
        public System.Guid ID { get; set; }
        public string IDBAD { get; set; }
        public Nullable<System.Guid> IDUSER { get; set; }
        public Nullable<System.Guid> GUIDBAD { get; set; }
        public Nullable<int> TYPEBAD { get; set; }
        public Nullable<bool> LECTURE { get; set; }
        public Nullable<bool> ECRITURE { get; set; }
        public Nullable<System.DateTime> DATEFIN { get; set; }
    }
}
