//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAD_DIRECT
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> MASTERKEY { get; set; }
        public Nullable<System.Guid> USERID { get; set; }
        public Nullable<System.Guid> ENVOIID { get; set; }
        public Nullable<System.DateTime> DATEHEURE { get; set; }
        public string DESTS { get; set; }
        public Nullable<int> COUNTFILES { get; set; }
        public string REFERENCE { get; set; }
    }
}
