//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAD_DOWNLOAD
    {
        public int IDDOWN { get; set; }
        public Nullable<int> IDFICHIER { get; set; }
        public Nullable<int> IDDOSSIER { get; set; }
        public string HASHDOWNLOAD { get; set; }
        public Nullable<int> LOC { get; set; }
        public string USERKEY { get; set; }
        public Nullable<bool> FREEACCOUNT { get; set; }
        public Nullable<bool> ALIAS { get; set; }
    }
}
