//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOITES_A_DOCS
    {
        public int IDDOC { get; set; }
        public string NOM_DOC { get; set; }
        public string CHEMIN { get; set; }
        public string HASHCLIENT { get; set; }
        public Nullable<System.DateTime> DATE_ENVOI { get; set; }
        public string HEURE_ENVOI { get; set; }
        public string HASHMASTER { get; set; }
        public Nullable<bool> CLIENT { get; set; }
        public Nullable<int> TAILLE { get; set; }
        public Nullable<bool> LU { get; set; }
        public Nullable<System.DateTime> DATE_RECEP { get; set; }
        public string HEURE_RECEP { get; set; }
        public string HASHVALUE { get; set; }
        public Nullable<int> IDEXPEDITEUR { get; set; }
    }
}
