//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BWALL_COMMENTAIRES
    {
        public int IDCOMM { get; set; }
        public string HASHFILE { get; set; }
        public Nullable<System.DateTime> DATE_COMMENTAIRE { get; set; }
        public string HEURE_COMMENTAIRE { get; set; }
        public string MESSAGE { get; set; }
        public string HASHCOMM { get; set; }
        public string HASHREDACTEUR { get; set; }
        public Nullable<bool> PRIVE { get; set; }
        public Nullable<bool> COMM_CLOTURE { get; set; }
        public Nullable<System.DateTime> DATE_EDITION { get; set; }
        public string HEURE_EDITION { get; set; }
        public string HASHREFERE { get; set; }
        public Nullable<bool> MODIFIE { get; set; }
        public Nullable<int> ETAPE { get; set; }
        public Nullable<int> IDCATEGORIE { get; set; }
        public Nullable<bool> TRANSFERT { get; set; }
        public Nullable<bool> PJ { get; set; }
    }
}
