//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BWALL_ABO_MODELE
    {
        public int ID_ABO_MODELE { get; set; }
        public Nullable<int> IDRUBRIQUE { get; set; }
        public Nullable<int> IDSOUSRUBRIQUE { get; set; }
        public string MASTERKEY { get; set; }
        public string INTITULE { get; set; }
        public Nullable<int> NB_RECURRENCE { get; set; }
        public Nullable<int> TYPE_RECURRENCE { get; set; }
    }
}
