//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BWALL_QUICKSAVE
    {
        public int ID { get; set; }
        public string HASHFILE { get; set; }
        public Nullable<System.DateTime> DATE_QUICKSAVE { get; set; }
        public string HEURE_QUICKSAVE { get; set; }
        public string MESSAGE { get; set; }
        public string HASHINITIATEUR { get; set; }
        public Nullable<int> IDOBJET { get; set; }
        public Nullable<int> TYPERAPPORT { get; set; }
        public string MASTERKEY { get; set; }
        public Nullable<bool> CLOTURE { get; set; }
        public Nullable<System.DateTime> DATE_CLOTURE { get; set; }
    }
}
