//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BWALL_FILES_CONTRAT
    {
        public int ID_FILE_CONTRAT { get; set; }
        public string MASTERKEY { get; set; }
        public Nullable<int> IDMODELE { get; set; }
        public string INTITULE { get; set; }
        public Nullable<int> QTE { get; set; }
        public Nullable<System.DateTime> DATE_DEBUT { get; set; }
        public Nullable<System.DateTime> DATE_FIN { get; set; }
    }
}
