//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BWALL_ABO_SOUS_RUBRIQUE
    {
        public int ID_ABO_SOUS_RUBRIQUE { get; set; }
        public Nullable<int> ID_RUBRIQUE { get; set; }
        public string DESIGNATION { get; set; }
        public string MASTERKEY { get; set; }
    }
}
