//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BWALL_RUBRIQUES
    {
        public int IDRUBRIQUE { get; set; }
        public Nullable<int> VALEUR { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<System.Guid> TYPE_FORMULAIRE { get; set; }
        public Nullable<int> ORDRE { get; set; }
        public string MASTERKEY { get; set; }
        public Nullable<bool> DEMANDE { get; set; }
        public Nullable<bool> ACTIVITE { get; set; }
    }
}
