//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BWALL_ACTIVITES
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> idtype { get; set; }
        public Nullable<int> idsoustype { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public string heure_creation { get; set; }
        public Nullable<System.DateTime> date_prise_en_charge { get; set; }
        public Nullable<System.DateTime> dateheure { get; set; }
        public string commentaire { get; set; }
        public string hashdeposant { get; set; }
        public string masterkey { get; set; }
        public string objet { get; set; }
        public string hashencharge { get; set; }
        public Nullable<bool> cloture { get; set; }
        public string hashinitiateur { get; set; }
        public string hashtechprecedent { get; set; }
        public string hashcloturant { get; set; }
        public Nullable<System.DateTime> date_cloture { get; set; }
        public string heure_cloture { get; set; }
        public string commcloture { get; set; }
    }
}
