//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BWALL_FILES_PJ
    {
        public int IDPJ { get; set; }
        public string HASHFILE { get; set; }
        public string HASHMESSAGE { get; set; }
        public string NOM_FICHIER { get; set; }
        public Nullable<bool> TEMP { get; set; }
        public string SESSIONID { get; set; }
    }
}
