//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BWALL_RUBRIQUES_DROITS
    {
        public int IDDROIT { get; set; }
        public Nullable<int> IDRUBRIQUE { get; set; }
        public string HASHCORRES { get; set; }
        public Nullable<int> NIVEAU { get; set; }
    }
}
