//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CACHE_MAILS
    {
        public int IDMAIL { get; set; }
        public Nullable<int> IDUSER { get; set; }
        public string MESSAGEID { get; set; }
        public string MSG_FROM { get; set; }
        public Nullable<System.DateTime> MSG_DATE { get; set; }
        public string MSG_OBJET { get; set; }
        public Nullable<int> MSG_INDEX { get; set; }
        public string MSG_BODY { get; set; }
    }
}
