//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public int idclient { get; set; }
        public Nullable<int> MASTER { get; set; }
        public Nullable<int> IDX_CLIENT { get; set; }
        public string COMPLEMENT_ADRESSE { get; set; }
        public string ADRESSE2 { get; set; }
        public string COMPLEMENT_ADRESSE2 { get; set; }
        public string TELEPHONE2 { get; set; }
        public string BP { get; set; }
        public string BP2 { get; set; }
        public string VILLE2 { get; set; }
        public string PAYS2 { get; set; }
        public string CP2 { get; set; }
        public string ACTIVITE { get; set; }
        public Nullable<int> TYPE_CLIENT { get; set; }
        public string FORME_JURIDIQUE { get; set; }
        public string COMMERCIAL { get; set; }
        public string NUM_TVA { get; set; }
        public string RIB { get; set; }
        public Nullable<bool> ACTIF { get; set; }
        public string NOM { get; set; }
        public string ADRESSE { get; set; }
        public string CP { get; set; }
        public string VILLE { get; set; }
        public string TELEPHONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string SITE_WEB { get; set; }
        public string PAYS { get; set; }
        public string CODE_CLIENT { get; set; }
        public string HASHKEY { get; set; }
        public string LOGIN_FICHIERS { get; set; }
        public string MDP_FICHIERS { get; set; }
        public string LOGIN_DOC_ADMIN { get; set; }
        public string MDP_DOC_ADMIN { get; set; }
        public Nullable<bool> REDIR { get; set; }
        public string HASH_REDIR { get; set; }
        public string EMAIL_BAP { get; set; }
        public Nullable<bool> PUBLIQUE { get; set; }
        public string DOMAINE { get; set; }
    }
}
