//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_CORRESPONDANTS
    {
        public int idcorres { get; set; }
        public Nullable<int> IDX_CLIENT { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string FONCTION { get; set; }
        public string TELEPHONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string TITRE { get; set; }
        public string HASHKEY { get; set; }
        public string LOGIN_WIN { get; set; }
        public string MDP_WIN { get; set; }
        public string LOGIN_MESS { get; set; }
        public string MDP_MESS { get; set; }
    }
}
