//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_POSTAUX
    {
        public int ID { get; set; }
        public string NOM_VILLE { get; set; }
        public string CODE_POSTAL { get; set; }
        public string DEPARTEMENT { get; set; }
        public string INSEE { get; set; }
    }
}
