//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMANDES
    {
        public int idcommande { get; set; }
        public int idclient { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string demande_init { get; set; }
        public string intitule { get; set; }
        public Nullable<int> en_cours { get; set; }
        public Nullable<int> annulation { get; set; }
        public Nullable<int> acceptation { get; set; }
        public Nullable<System.DateTime> date_annulation { get; set; }
        public Nullable<System.DateTime> date_acceptation { get; set; }
    }
}
