//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPTE
    {
        public int numCompte { get; set; }
        public string idCompte { get; set; }
        public string catCompte { get; set; }
        public string passCompte { get; set; }
        public string nomClient { get; set; }
    }
}
