//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPTES_BOITES_A_DOCS
    {
        public int IDCOMPTE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string EMAIL { get; set; }
        public string MDP { get; set; }
        public Nullable<int> IDCLIENT { get; set; }
        public string HASHCOMPTE { get; set; }
        public Nullable<System.DateTime> DATE_FIN { get; set; }
        public Nullable<int> TYPE_BAD { get; set; }
        public Nullable<int> AFFAIRE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<int> IDCORRES { get; set; }
        public Nullable<int> IDAFFAIRE { get; set; }
    }
}
