//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRAT
    {
        public int id_contrat { get; set; }
        public int id_master { get; set; }
        public int id_client { get; set; }
        public int id_famille_contrat { get; set; }
        public string nom_contrat { get; set; }
        public System.DateTime date_debut_contrat { get; set; }
        public System.DateTime date_fin_contrat { get; set; }
    }
}
