//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTS_ISOLES
    {
        public int IDCONTACT { get; set; }
        public string CIVILITE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string EMAIL { get; set; }
        public string TELEPHONE { get; set; }
        public string SOCIETE { get; set; }
        public string HASHKEY { get; set; }
        public string ADRESSE { get; set; }
        public string CP { get; set; }
        public string VILLE { get; set; }
        public string MASTERKEY { get; set; }
    }
}
