//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTS_PRIVES
    {
        public System.Guid ID { get; set; }
        public string USERKEY { get; set; }
        public string SOCIETE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string EMAIL1 { get; set; }
        public string EMAIL2 { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public Nullable<bool> ACTIF { get; set; }
        public Nullable<bool> CORBEILLE { get; set; }
        public string IDICEWARP { get; set; }
    }
}
