//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATS_ABONNEMENTS_CLIENTS
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDCONTRATABO { get; set; }
        public Nullable<System.Guid> IDOBJET { get; set; }
        public Nullable<System.DateTime> DATE_SOUSCRIPTION { get; set; }
        public string COMMENTAIRE { get; set; }
        public string REFERENCE { get; set; }
        public string PERIODICITE { get; set; }
        public Nullable<System.DateTime> DATE_ECHEANCE { get; set; }
        public string DUREE { get; set; }
        public Nullable<bool> RENOUVELEMENT_AUTO { get; set; }
        public Nullable<int> QUANTITE { get; set; }
        public Nullable<decimal> MONTANTHT { get; set; }
        public string FACTURATION { get; set; }
    }
}
