//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMANDES_CLIENT
    {
        public int IDDEMANDE { get; set; }
        public Nullable<int> IDMASTER { get; set; }
        public Nullable<int> IDDEMANDEUR { get; set; }
        public Nullable<System.DateTime> DATE_DEMANDE { get; set; }
        public string IMPORTANCE { get; set; }
        public string MESSAGE { get; set; }
        public string TICKET { get; set; }
        public string ETAT { get; set; }
        public string NATURE { get; set; }
    }
}
