//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAILS_LIGNES_RAPPORTS
    {
        public int IDDETAILS { get; set; }
        public Nullable<int> IDLIGNERAPPORT { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<bool> FAITE { get; set; }
        public Nullable<bool> NA { get; set; }
        public Nullable<int> IDMODELE { get; set; }
        public Nullable<int> ORDRE { get; set; }
    
        public virtual RAPPORTS_LIGNES RAPPORTS_LIGNES { get; set; }
    }
}
