//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIPLOMES_CANDIDATS
    {
        public int ID_DIPLOME_CANDIDAT { get; set; }
        public Nullable<int> ID_DIPLOME { get; set; }
        public Nullable<int> ID_CANDIDAT { get; set; }
    }
}
