//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOSSIERS_DEFAUTS_BAD
    {
        public int IDDOSSIER { get; set; }
        public Nullable<int> IDMODELE { get; set; }
        public string MASTERKEY { get; set; }
        public string NOM_DOSSIER { get; set; }
    
        public virtual MODELES_DOSSIERS_DEFAUTS_BAD MODELES_DOSSIERS_DEFAUTS_BAD { get; set; }
    }
}
