//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOSSIERS_FICHIERS_COMMUNS
    {
        public int IDDOSSIER { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<int> IDMASTER { get; set; }
        public Nullable<int> IDGROUPE { get; set; }
    }
}
