//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOWNLOAD
    {
        public int IDDOWNLOAD { get; set; }
        public string HASHDOWNLOAD { get; set; }
        public string CHEMIN { get; set; }
        public string FICHIER { get; set; }
        public string TYPE_FICHIER { get; set; }
        public string HEURE_DEBUT { get; set; }
        public string HEURE_FIN { get; set; }
        public Nullable<System.DateTime> DATE_DOWNLOAD { get; set; }
    }
}
