//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DROITS_FICHES
    {
        public int IDROIT { get; set; }
        public Nullable<int> IDFICHE { get; set; }
        public Nullable<int> TYPE_FICHE { get; set; }
        public Nullable<int> IDGROUPE { get; set; }
    
        public virtual GROUPES_SECURITE GROUPES_SECURITE { get; set; }
    }
}
