//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DROITS_DOSSIERS_BAD_EXTERNES
    {
        public int IDDROITUSEREXTERNE { get; set; }
        public Nullable<int> IDDROIT { get; set; }
        public Nullable<int> IDUSER { get; set; }
        public Nullable<int> DROIT { get; set; }
        public string HASHCLI { get; set; }
    }
}
