//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DROITS_DOSSIERS_GED
    {
        public int IDDROIT { get; set; }
        public string CHEMIN { get; set; }
        public Nullable<int> MODE { get; set; }
        public string NOM_DOSSIER { get; set; }
        public Nullable<int> DEPTH { get; set; }
        public string HASHOBJET { get; set; }
        public Nullable<bool> LOCKED { get; set; }
        public string MDP { get; set; }
    }
}
