//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENEMENTS_BAD
    {
        public int IDEVENEMENT { get; set; }
        public string TYPE_EVT { get; set; }
        public string HASHEVT { get; set; }
        public Nullable<System.DateTime> DATE_EVT { get; set; }
        public string HEURE_EVT { get; set; }
        public Nullable<int> ID_INITIATEUR { get; set; }
        public string HASHCLIENT { get; set; }
        public string NOM_DOSSIER { get; set; }
        public Nullable<bool> CLIENT { get; set; }
        public string HASHAFFAIRE { get; set; }
        public string ANCIEN_NOM_DOSSIER { get; set; }
        public string HASHDEST { get; set; }
        public string CHEMIN { get; set; }
    }
}
