//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAMILLE_INTERVENTION
    {
        public int id_famille_intervention { get; set; }
        public int id_master { get; set; }
        public string nom_famille_intervention { get; set; }
        public int id_tarification { get; set; }
        public bool visible { get; set; }
    
        public virtual FAMILLE_INTERVENTION FAMILLE_INTERVENTION1 { get; set; }
        public virtual FAMILLE_INTERVENTION FAMILLE_INTERVENTION2 { get; set; }
        public virtual FAMILLE_INTERVENTION FAMILLE_INTERVENTION11 { get; set; }
        public virtual FAMILLE_INTERVENTION FAMILLE_INTERVENTION3 { get; set; }
    }
}
