//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHIERS_BAD
    {
        public int IDFICHIER { get; set; }
        public string CHEMIN { get; set; }
        public string COMMENTAIRE { get; set; }
        public string NOM_FICHIER { get; set; }
        public string HASHEVT { get; set; }
        public string TYPE { get; set; }
        public Nullable<long> TAILLE { get; set; }
        public Nullable<bool> CLIENT { get; set; }
        public string HASHCLIENT { get; set; }
        public Nullable<int> VERSION { get; set; }
        public Nullable<bool> ARCHIVE { get; set; }
        public string NOM_ARCHIVE { get; set; }
        public Nullable<System.DateTime> DATE_MODIF { get; set; }
        public string HASHAFFAIRE { get; set; }
        public string HASHCREATEUR { get; set; }
        public Nullable<System.DateTime> DATE_CREATION { get; set; }
        public string HASHMODIFICATEUR { get; set; }
        public Nullable<bool> CORBEILLE { get; set; }
        public Nullable<bool> ENDED { get; set; }
    }
}
