//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHIERS_OUVERTS
    {
        public int idfichier_ouvert { get; set; }
        public Nullable<int> IDFICHIER { get; set; }
        public string USER_KEY { get; set; }
    
        public virtual FICHIERS FICHIERS { get; set; }
    }
}
