//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPES_SECURITE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROUPES_SECURITE()
        {
            this.DROITS_FICHES = new HashSet<DROITS_FICHES>();
            this.DROITS_GROUPES_SECURITES = new HashSet<DROITS_GROUPES_SECURITES>();
            this.GROUPES_SECURITE_MEMBRES = new HashSet<GROUPES_SECURITE_MEMBRES>();
        }
    
        public int IDGROUPE { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<int> MASTER { get; set; }
        public Nullable<int> IDADMIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DROITS_FICHES> DROITS_FICHES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DROITS_GROUPES_SECURITES> DROITS_GROUPES_SECURITES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPES_SECURITE_MEMBRES> GROUPES_SECURITE_MEMBRES { get; set; }
    }
}
