//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENTS_MODELES
    {
        public int ID_MODELE { get; set; }
        public Nullable<int> IDRUBRIQUE { get; set; }
        public Nullable<int> IDSOUSRUBRIQUE { get; set; }
        public string NOM_MODELE { get; set; }
        public string TEXTE { get; set; }
    }
}
