//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INCIDENTS()
        {
            this.INCIDENTS_COMMENTAIRES = new HashSet<INCIDENTS_COMMENTAIRES>();
        }
    
        public int IDINCIDENT { get; set; }
        public Nullable<int> IDMASTER { get; set; }
        public Nullable<int> IDUSER { get; set; }
        public Nullable<System.DateTime> DATE_INCIDENT { get; set; }
        public string HEURE_INCIDENT { get; set; }
        public string DESCRIPTION { get; set; }
        public string TICKET { get; set; }
        public Nullable<int> ETAT { get; set; }
        public string HASHKEY { get; set; }
        public Nullable<int> IDENCHARGE { get; set; }
        public Nullable<int> TYPE_INCIDENT { get; set; }
        public Nullable<System.DateTime> DATE_INTERVENTION { get; set; }
        public string COMPLEMENT_INTERVENTION { get; set; }
        public Nullable<int> IDRUBRIQUE { get; set; }
        public Nullable<int> IDSOUSRUBRIQUE { get; set; }
        public Nullable<bool> CLOTURE { get; set; }
        public Nullable<System.DateTime> DATE_CLOTURE { get; set; }
        public string HEURE_CLOTURE { get; set; }
        public Nullable<bool> CLIENT { get; set; }
        public Nullable<int> IDDEST { get; set; }
        public Nullable<int> TYPE_FORMULAIRE { get; set; }
        public Nullable<bool> INTERNE { get; set; }
        public Nullable<bool> TO_SUPPORT { get; set; }
        public string COMMENTAIRE_CLOTURE { get; set; }
        public Nullable<int> IDCLOTURANT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INCIDENTS_COMMENTAIRES> INCIDENTS_COMMENTAIRES { get; set; }
    }
}
