//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENTS_COMMENTAIRES
    {
        public int IDCOMMENTAIRE { get; set; }
        public Nullable<int> IDINCIDENT { get; set; }
        public Nullable<System.DateTime> DATE_COMMENTAIRE { get; set; }
        public string HEURE_COMMENTAIRE { get; set; }
        public string COMMENTAIRE { get; set; }
        public Nullable<int> ORIGINE { get; set; }
        public Nullable<int> TYPE_COMMENTAIRE { get; set; }
        public string PJ { get; set; }
        public Nullable<bool> PRIVE { get; set; }
        public string HASHMESSAGE { get; set; }
        public Nullable<bool> COMM_CLOTURE { get; set; }
    
        public virtual INCIDENTS INCIDENTS { get; set; }
    }
}
