//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERVENTIONS
    {
        public System.Guid ID { get; set; }
        public System.Guid TECHNICIEN { get; set; }
        public System.DateTime DATEHEURE { get; set; }
        public string TYPEINTER { get; set; }
        public System.Guid CLIENT { get; set; }
        public Nullable<int> TICKET { get; set; }
        public bool CLOTURE { get; set; }
        public string COMM_CLOTURE { get; set; }
        public string HASHCLOTURANT { get; set; }
        public Nullable<System.DateTime> DATECLOTURE { get; set; }
        public string DUREEINTER { get; set; }
    }
}
