//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERNE
    {
        public int idinterne { get; set; }
        public string NOM { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAX { get; set; }
        public string SITE_WEB { get; set; }
        public string ADRESSE { get; set; }
        public string COMPLEMENT { get; set; }
        public string BP { get; set; }
        public string CP { get; set; }
        public string VILLE { get; set; }
        public string PAYS { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ACTIF { get; set; }
        public Nullable<int> MASTER { get; set; }
        public string HASH { get; set; }
    }
}
