//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERVENTION
    {
        public int id_intervention { get; set; }
        public int id_master { get; set; }
        public int id_client { get; set; }
        public Nullable<int> id_famille_intervention { get; set; }
        public System.DateTime date { get; set; }
        public int heure { get; set; }
        public int minute { get; set; }
        public string technicien { get; set; }
        public string titre { get; set; }
        public string motif { get; set; }
        public string description { get; set; }
        public bool visible { get; set; }
    }
}
