//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERVENTIONS_MODELES
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> DATEMODELE { get; set; }
        public string TYPEINTER { get; set; }
        public string MATERIEL { get; set; }
        public string DETAILS { get; set; }
        public string TITRE { get; set; }
    }
}
