//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINKS
    {
        public int IDLINK { get; set; }
        public string NOM { get; set; }
        public string IMAGE { get; set; }
        public string URL { get; set; }
        public string OWNER { get; set; }
    }
}
