//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGS
    {
        public int IDLOG { get; set; }
        public Nullable<System.DateTime> DATE_LOG { get; set; }
        public string HEURE_LOG { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<int> IDUSER { get; set; }
        public string EVENEMENT { get; set; }
        public string PAGE { get; set; }
        public string CLASSE { get; set; }
        public string METHODE { get; set; }
        public string ERRORMETHODE { get; set; }
        public string IP { get; set; }
        public string URL { get; set; }
        public string ERRORMESSAGE { get; set; }
    }
}
