//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAILS
    {
        public int IDMAIL { get; set; }
        public string HASHCLIENT { get; set; }
        public Nullable<System.DateTime> DATE_MAIL { get; set; }
        public string OBJET { get; set; }
        public string CORPS { get; set; }
        public string IDMESSAGE { get; set; }
    }
}
