//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTERS
    {
        public Nullable<System.Guid> ID { get; set; }
        public int idmaster { get; set; }
        public string NOM { get; set; }
        public string ADRESSE { get; set; }
        public string CP { get; set; }
        public string VILLE { get; set; }
        public string DOSSIER { get; set; }
        public Nullable<bool> MODULE_PLANNING { get; set; }
        public Nullable<bool> MODULE_COLLABORATIF { get; set; }
        public Nullable<bool> MODULE_BAP { get; set; }
        public string CLE { get; set; }
        public string URL_PLANNING { get; set; }
        public string BASE { get; set; }
        public Nullable<bool> MODULE_FICHIERS { get; set; }
        public Nullable<int> TYPE_BAP { get; set; }
        public string WEBMAIL { get; set; }
        public string EMPLACEMENT_FICHIERS { get; set; }
        public Nullable<int> TYPE_WEBMAIL { get; set; }
        public Nullable<int> TYPE_ACCUEIL { get; set; }
        public string DOMAINE { get; set; }
        public Nullable<bool> PERSO_DEMARCHE_PROSPECTS { get; set; }
        public Nullable<bool> INDEX_AFFAIRES { get; set; }
        public Nullable<bool> INDEX_PROSPECTS { get; set; }
        public Nullable<bool> INDEX_ADHERENTS { get; set; }
        public Nullable<bool> INDEX_FOURNISSEURS { get; set; }
        public Nullable<bool> INDEX_TIERS { get; set; }
        public Nullable<bool> INDEX_CLIENTS { get; set; }
        public Nullable<bool> INDEX_PARTENAIRES { get; set; }
        public Nullable<bool> INDEX_INSTITUTIONNELS { get; set; }
        public Nullable<bool> INDEX_SOUSTRAITANTS { get; set; }
        public Nullable<bool> INDEX_INTERNE { get; set; }
        public string SERVEUR { get; set; }
        public string URL_CLIENT { get; set; }
        public string LOGO { get; set; }
        public Nullable<bool> GOD_MODE { get; set; }
        public Nullable<bool> NEW { get; set; }
        public string URL { get; set; }
        public Nullable<bool> ABO_WALL { get; set; }
        public Nullable<bool> ABO_SHARE { get; set; }
        public Nullable<bool> SUIVI_ACTIVITE { get; set; }
        public Nullable<bool> SUIVI_GENERATEUR { get; set; }
        public Nullable<System.Guid> CONTACT_PUB { get; set; }
        public string METIER { get; set; }
        public string POINTSFORTS { get; set; }
        public string SLOGAN { get; set; }
        public bool R1 { get; set; }
        public bool R2 { get; set; }
        public bool R3 { get; set; }
        public bool R4 { get; set; }
        public bool ANNUAIRE { get; set; }
        public string MAIL_CONTACT { get; set; }
        public string TELEPHONE_CONTACT { get; set; }
        public string SITE_INTERNET { get; set; }
        public bool PUBLIER_MAIL { get; set; }
    }
}
