//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTERS_SITES
    {
        public int IDSITE { get; set; }
        public Nullable<int> IDMASTER { get; set; }
        public string DESIGNATION { get; set; }
        public string ADRESSE_SERVEUR { get; set; }
        public string IP_SITE { get; set; }
    }
}
