//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIELS
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> marque { get; set; }
        public Nullable<System.Guid> modele { get; set; }
        public string typedd { get; set; }
        public Nullable<int> capacitedd { get; set; }
        public Nullable<int> capaciteram { get; set; }
        public string tag { get; set; }
        public Nullable<System.DateTime> datemiseenservice { get; set; }
        public Nullable<System.DateTime> datefingarantie { get; set; }
        public string formule { get; set; }
        public Nullable<System.Guid> idproprietaire { get; set; }
        public string typegarantie { get; set; }
        public string n_dossier { get; set; }
        public Nullable<System.DateTime> datefinlocation { get; set; }
        public Nullable<System.DateTime> daterenouvellement { get; set; }
        public Nullable<System.DateTime> datealerterenouvellement { get; set; }
        public Nullable<System.DateTime> datealertefincontrat { get; set; }
        public Nullable<System.DateTime> datealertefingarantie { get; set; }
        public string nom_machine { get; set; }
        public Nullable<int> id_OCS { get; set; }
    }
}
