//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELES_DOSSIERS_DEFAUTS_BAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODELES_DOSSIERS_DEFAUTS_BAD()
        {
            this.DOSSIERS_DEFAUTS_BAD = new HashSet<DOSSIERS_DEFAUTS_BAD>();
        }
    
        public int IDMODELE { get; set; }
        public string NOMMODELE { get; set; }
        public string MASTERKEY { get; set; }
        public Nullable<int> DEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOSSIERS_DEFAUTS_BAD> DOSSIERS_DEFAUTS_BAD { get; set; }
    }
}
