//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULES
    {
        public int IDMODULE { get; set; }
        public string NOM_MODULE { get; set; }
        public string NOM_ACCUEIL { get; set; }
        public string IMG_MODULE { get; set; }
        public string IMG_MIN_MODULE { get; set; }
        public string BACKCOLOR { get; set; }
        public string URL { get; set; }
        public Nullable<bool> OPTION_URL { get; set; }
        public string ATTRIB_KEY { get; set; }
        public string ATTRIB_VALUE { get; set; }
        public string URL_OPTIONS { get; set; }
        public Nullable<bool> ADMIN { get; set; }
        public Nullable<bool> FREEACCOUNT { get; set; }
        public Nullable<bool> SUPPORT { get; set; }
    }
}
