//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATIONS
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> DATE_HEURE { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<bool> GLOBAL { get; set; }
        public Nullable<System.Guid> TYPE { get; set; }
    }
}
