//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETS_DASHBOARD_HISTO
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDDASH { get; set; }
        public Nullable<System.DateTime> DATE_HISTO { get; set; }
        public Nullable<System.Guid> OPERATEUR { get; set; }
        public Nullable<int> OPERATION { get; set; }
        public Nullable<System.DateTime> DATE_MESSAGE { get; set; }
        public Nullable<int> IMPORTANCE { get; set; }
        public Nullable<int> RUBRIQUE { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> DATE_1 { get; set; }
        public Nullable<System.DateTime> DATE_2 { get; set; }
    }
}
