//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETS
    {
        public Nullable<System.Guid> ID { get; set; }
        public int IDOBJET { get; set; }
        public string CIVILITE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string RAISON_SOCIALE { get; set; }
        public string ADRESSE { get; set; }
        public string COMPLEMENT_ADRESSE { get; set; }
        public string BP { get; set; }
        public string CP { get; set; }
        public string VILLE { get; set; }
        public string PAYS { get; set; }
        public Nullable<int> TYPE_ADRESSE_SECONDAIRE { get; set; }
        public string ADRESSE2 { get; set; }
        public string COMPLEMENT_ADRESSE2 { get; set; }
        public string BP2 { get; set; }
        public string CP2 { get; set; }
        public string VILLE2 { get; set; }
        public string PAYS2 { get; set; }
        public string ACTIVITE { get; set; }
        public string FORME_JURIDIQUE { get; set; }
        public string NUM_TVA { get; set; }
        public string TELEPHONE { get; set; }
        public string TELEPHONE2 { get; set; }
        public string FAX { get; set; }
        public string SITE_WEB { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ACTIF { get; set; }
        public string CODE_CLIENT { get; set; }
        public Nullable<int> MASTER { get; set; }
        public string HASHKEY { get; set; }
        public Nullable<int> TYPE_FICHE { get; set; }
        public Nullable<int> ANCIEN_ID { get; set; }
        public Nullable<int> TYPE_OBJET { get; set; }
        public string DOMAINE { get; set; }
        public string SIRET { get; set; }
        public Nullable<int> ORIGINE { get; set; }
        public Nullable<int> PROSPECTION { get; set; }
        public string DATE_DE_NAISSANCE { get; set; }
        public Nullable<System.DateTime> DATE_CREATION { get; set; }
        public Nullable<System.DateTime> DATE_MODIFICATION { get; set; }
        public string RIB { get; set; }
        public string APE { get; set; }
        public string CONTACT_PRINCIPAL { get; set; }
        public Nullable<bool> EXPORT { get; set; }
        public string COMMENTAIRES { get; set; }
        public Nullable<bool> BAD_ACTIVE { get; set; }
        public Nullable<int> IDPROPRIETAIRE { get; set; }
        public string HASHPROPRIETAIRE { get; set; }
        public Nullable<int> IDSIEGE { get; set; }
        public string HASHSIEGE { get; set; }
        public string DATE_MAJ { get; set; }
        public string NOM_MAJ { get; set; }
        public Nullable<int> TYPE_SECURITE { get; set; }
        public string HASHMODELE_SEC { get; set; }
        public Nullable<System.DateTime> DATE_SUPPRESSION { get; set; }
        public Nullable<bool> CORBEILLE { get; set; }
        public Nullable<System.DateTime> DATE_ARCHIVAGE { get; set; }
        public Nullable<System.Guid> VERROU { get; set; }
        public Nullable<bool> CONTRAT { get; set; }
        public Nullable<System.Guid> ENTITE { get; set; }
        public Nullable<System.Guid> CONDITION { get; set; }
    }
}
