//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETS_CORRESPONDANTS
    {
        public Nullable<System.Guid> ID { get; set; }
        public int IDCORRES { get; set; }
        public Nullable<int> IDOBJET { get; set; }
        public string CIVILITE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string FONCTION { get; set; }
        public string TELEPHONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string HASHKEY { get; set; }
        public string LOGIN_WIN { get; set; }
        public string MDP_WIN { get; set; }
        public string LOGIN_MESS { get; set; }
        public string MDP_MESS { get; set; }
        public string ADRESSE { get; set; }
        public string COMPLEMENT { get; set; }
        public string CP { get; set; }
        public string VILLE { get; set; }
        public string PAYS { get; set; }
        public Nullable<bool> ACTIVATION_BAD { get; set; }
        public Nullable<bool> EXPORT { get; set; }
        public string MDP { get; set; }
        public Nullable<bool> ENVOI_INVIT { get; set; }
        public string HASHACTIV { get; set; }
        public string HASHUSERBNET { get; set; }
        public string DOMAINE { get; set; }
        public Nullable<System.DateTime> REV { get; set; }
        public Nullable<System.DateTime> DATE_SUPPRESSION { get; set; }
        public Nullable<bool> ACTIF { get; set; }
        public Nullable<bool> CORBEILLE { get; set; }
        public Nullable<System.DateTime> DATE_ARCHIVAGE { get; set; }
        public Nullable<System.Guid> VERROU { get; set; }
        public bool CORRES_TECHNIQUE { get; set; }
        public bool CORRES_COMMERCIAL { get; set; }
        public bool CORRES_ADMINISTRATIF { get; set; }
        public bool CORRES_PRINCIPAL { get; set; }
    }
}
