//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETS_CORRESPONDANTS_ICEWARP
    {
        public int ID_CORRES_ICEWARP { get; set; }
        public string HASHCORRESICEWARP { get; set; }
        public string USERKEY { get; set; }
        public string HASHCORRES { get; set; }
        public string ID_ICEWARP { get; set; }
    }
}
