//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTION_CONTRAT
    {
        public int id_option_contrat { get; set; }
        public int id_contrat { get; set; }
        public int id_option_famille_contrat { get; set; }
        public string valeur_option { get; set; }
    }
}
