//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMS
    {
        public int IDPARAM { get; set; }
        public string HASHMASTER { get; set; }
        public Nullable<bool> REP_REFERENCE { get; set; }
        public Nullable<bool> BAD_LECTURE { get; set; }
        public Nullable<bool> BAD_ABO_AUTO { get; set; }
    }
}
