//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMALINKS
    {
        public int IDPERMALINK { get; set; }
        public string PERMALINK { get; set; }
        public string NOM_PARTAGE { get; set; }
        public Nullable<int> MASTER { get; set; }
        public Nullable<int> IDOBJET { get; set; }
    }
}
