//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSO_WORKFLOW
    {
        public int IDPERSO { get; set; }
        public string HASHMASTER { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<int> TYPE_OBJET { get; set; }
    }
}
