//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PieceJointe
    {
        public Nullable<System.Guid> contenuid { get; set; }
        public Nullable<System.Guid> objetlieid { get; set; }
        public string typeobjetlieid { get; set; }
        public string typePiece { get; set; }
        public System.Guid id { get; set; }
        public System.DateTime datecreation { get; set; }
        public System.DateTime datemodification { get; set; }
        public string personneCreation { get; set; }
        public string personneModification { get; set; }
        public string checksum { get; set; }
        public string mime { get; set; }
        public Nullable<bool> pardefaut { get; set; }
    }
}
