//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicites
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> masterkey { get; set; }
        public string domain { get; set; }
        public Nullable<System.DateTime> debut { get; set; }
        public Nullable<System.DateTime> fin { get; set; }
        public string image { get; set; }
        public string url { get; set; }
    }
}
