//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAPPORTS_LIGNES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAPPORTS_LIGNES()
        {
            this.DETAILS_LIGNES_RAPPORTS = new HashSet<DETAILS_LIGNES_RAPPORTS>();
        }
    
        public int IDLIGNE { get; set; }
        public Nullable<int> IDRAPPORT { get; set; }
        public string DESIGNATION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAILS_LIGNES_RAPPORTS> DETAILS_LIGNES_RAPPORTS { get; set; }
    }
}
