//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sendto_destinataires
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> idsend { get; set; }
        public string destinataire { get; set; }
        public Nullable<bool> lu { get; set; }
        public Nullable<bool> securise { get; set; }
        public string code { get; set; }
        public string reference { get; set; }
    }
}
