//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sendto
    {
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> date_envoi { get; set; }
        public string expediteur { get; set; }
        public string ip { get; set; }
        public string masterkey { get; set; }
        public Nullable<int> nbfichiers { get; set; }
        public string reference { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
