//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHAREDLINKS
    {
        public int IDSHAREDLINK { get; set; }
        public string HASHLINK { get; set; }
        public Nullable<System.DateTime> DATE_FIN { get; set; }
    }
}
