//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPORTS_INTERVENTIONS
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> entite { get; set; }
        public string ticket { get; set; }
        public Nullable<System.Guid> client { get; set; }
        public Nullable<System.Guid> technicien { get; set; }
        public Nullable<System.DateTime> date_intervention { get; set; }
        public string duree_intervention { get; set; }
        public string descriptif { get; set; }
        public string actions { get; set; }
        public string commercial { get; set; }
        public Nullable<bool> contrat { get; set; }
        public Nullable<bool> contratastreinte { get; set; }
        public Nullable<bool> horscontrat { get; set; }
        public Nullable<bool> depannage { get; set; }
        public Nullable<bool> entretien { get; set; }
        public Nullable<bool> config { get; set; }
        public Nullable<bool> sauvegarde { get; set; }
        public Nullable<bool> serveur { get; set; }
        public Nullable<bool> posteclient { get; set; }
        public Nullable<bool> securite { get; set; }
        public Nullable<bool> reseau { get; set; }
        public Nullable<bool> scan { get; set; }
        public Nullable<bool> messagerie { get; set; }
        public Nullable<bool> moa { get; set; }
        public Nullable<bool> moe { get; set; }
    }
}
