//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPORTS_INTERVENTIONS
    {
        public System.Guid id { get; set; }
        public Nullable<int> id_master { get; set; }
        public Nullable<System.Guid> client { get; set; }
        public Nullable<System.Guid> technicien { get; set; }
        public Nullable<System.DateTime> date_intervention { get; set; }
    }
}
