//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TACHES_SUIVIS
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDMODELE { get; set; }
        public Nullable<System.Guid> IDCLIENT { get; set; }
        public string INTITULE { get; set; }
        public string HEURE_CREATION { get; set; }
        public string HASHINITIATEUR { get; set; }
        public Nullable<System.DateTime> DATE_CREATION { get; set; }
        public Nullable<bool> CLOTURE { get; set; }
        public string HASHTECHPRECEDENT { get; set; }
        public Nullable<System.DateTime> DATE_PRISE_EN_CHARGE { get; set; }
        public string MASTERKEY { get; set; }
        public string COMMCLOTURE { get; set; }
        public string HASHCLOTURANT { get; set; }
    }
}
