//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TACHE_FAMILLE_INTERVENTION
    {
        public int id_tache_famille_intervention { get; set; }
        public int id_famille_intervention { get; set; }
        public string nom_tache_famille_intervention { get; set; }
        public int etape { get; set; }
        public bool obligatoire { get; set; }
    }
}
