//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TACHES_MODELES
    {
        public System.Guid ID { get; set; }
        public string INTITULE { get; set; }
        public string MASTERKEY { get; set; }
        public Nullable<System.Guid> IDOBJET { get; set; }
        public Nullable<bool> VALIDATE { get; set; }
    }
}
