//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_UPLOAD_GED
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEMP_UPLOAD_GED()
        {
            this.TEMP_UPLOAD_GED_MOTS = new HashSet<TEMP_UPLOAD_GED_MOTS>();
        }
    
        public int IDTEMP { get; set; }
        public string NOM_FICHIER { get; set; }
        public string COMMENTAIRE { get; set; }
        public string TAILLE_FICHIER { get; set; }
        public string SESSIONID { get; set; }
        public string CHEMIN_DISQUE { get; set; }
        public string CHEMIN_DEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMP_UPLOAD_GED_MOTS> TEMP_UPLOAD_GED_MOTS { get; set; }
    }
}
