//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_UPLOADER
    {
        public int IDTEMP { get; set; }
        public string HASHUPLOAD { get; set; }
        public string HASHOBJET { get; set; }
        public string USERKEY { get; set; }
        public Nullable<bool> ISAFFAIRE { get; set; }
        public Nullable<bool> ISFREE { get; set; }
        public string APP_CHEMIN { get; set; }
        public string EMPLACEMENT { get; set; }
        public string APP_RACINE { get; set; }
        public Nullable<int> IDDOSSIER { get; set; }
    }
}
