//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATES
    {
        public int IDTEMPLATE { get; set; }
        public string DESIGNATION { get; set; }
        public string PROSPECTS { get; set; }
        public string CLIENTS { get; set; }
        public string FOURNISSEURS { get; set; }
        public string AFFAIRES { get; set; }
        public string BOITE_A_DOCS { get; set; }
        public string APPELS { get; set; }
        public string MAILS { get; set; }
        public string ARCHIVES { get; set; }
        public string TIERS { get; set; }
        public string PARTENAIRES { get; set; }
        public string INSTITUTIONNELS { get; set; }
        public string SOUSTRAITANTS { get; set; }
        public string INTERNE { get; set; }
    }
}
