//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_REDIR_SHARE
    {
        public int IDREDIR { get; set; }
        public string HASHREDIR { get; set; }
        public string HASHCLIENT { get; set; }
        public Nullable<System.DateTime> DATE_EXPIRE { get; set; }
        public string HASHCOMPTE { get; set; }
        public string EMAIL_INIT { get; set; }
    }
}
