//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_UPLOAD_GED_MOTS
    {
        public int IDMOT { get; set; }
        public Nullable<int> IDTEMP { get; set; }
        public string MOTCLE { get; set; }
    
        public virtual TEMP_UPLOAD_GED TEMP_UPLOAD_GED { get; set; }
    }
}
