//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_NOTIFICATIONS_BAD
    {
        public int IDTEMP { get; set; }
        public string SESSIONID { get; set; }
        public string NOM_FICHIER { get; set; }
        public string CHEMIN { get; set; }
        public string TYPE_FICHIER { get; set; }
    }
}
