//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS
    {
        public int IDTICKET { get; set; }
        public string NUM_TICKET { get; set; }
        public Nullable<System.DateTime> DATE_VALIDITE { get; set; }
        public string HASHAFFAIRE { get; set; }
        public string EMAIL { get; set; }
    }
}
