//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TODO
    {
        public int IDTODO { get; set; }
        public string USERKEY { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> DATE_TODO { get; set; }
        public string HASHTODO { get; set; }
        public string EMPLACEMENT { get; set; }
        public string HEURE_TODO { get; set; }
        public bool VALIDE { get; set; }
        public Nullable<bool> FAIT { get; set; }
        public Nullable<bool> ANNULE { get; set; }
        public Nullable<bool> ENCHARGE { get; set; }
        public Nullable<System.DateTime> DATE_CLOTURE { get; set; }
    }
}
