//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPES_OBJETS_COMPORTEMENTS
    {
        public int ID_COMPORTEMENT { get; set; }
        public Nullable<int> ID_TYPE_OBJET { get; set; }
        public Nullable<int> IDMASTER { get; set; }
        public Nullable<int> COMPORTEMENT { get; set; }
    }
}
