//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOAD_TEMP
    {
        public int IDTEMP { get; set; }
        public string HASHUPLOAD { get; set; }
        public string FILENAME { get; set; }
        public string TAILLE { get; set; }
    }
}
