//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOAD_GED
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UPLOAD_GED()
        {
            this.UPLOAD_GED_MOTS = new HashSet<UPLOAD_GED_MOTS>();
        }
    
        public int IDUPLOAD { get; set; }
        public string NOM_FICHIER { get; set; }
        public string COMMENTAIRE { get; set; }
        public string TAILLE_FICHIER { get; set; }
        public Nullable<int> IDMASTER { get; set; }
        public Nullable<int> IDUSER { get; set; }
        public Nullable<System.DateTime> DATE_ENVOI { get; set; }
        public string HEURE_ENVOI { get; set; }
        public string CHEMIN { get; set; }
        public string IDTEMP { get; set; }
        public string HASHOBJET { get; set; }
        public Nullable<int> VERSION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UPLOAD_GED_MOTS> UPLOAD_GED_MOTS { get; set; }
    }
}
