//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_EXTERNES_PARAMS
    {
        public int IDPARAM { get; set; }
        public string USERKEY { get; set; }
        public string ONEDRIVE_TOKEN { get; set; }
        public string ONEDRIVE_REFRESH_TOKEN { get; set; }
        public string GOOGLEDRIVE_TOKEN { get; set; }
        public string GOOGLEDRIVE_REFRESH_TOKEN { get; set; }
        public string DROPBOX_TOKEN { get; set; }
    }
}
