//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_EXTERNES
    {
        public Nullable<System.Guid> ID { get; set; }
        public int IDUSER { get; set; }
        public string CIVILITE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> MASTER { get; set; }
        public string CLE { get; set; }
        public string SOCIETE { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> ACTIF { get; set; }
        public Nullable<bool> SUPPORT { get; set; }
        public Nullable<System.DateTime> LASTLOGDATE { get; set; }
        public string LASTLOGHOUR { get; set; }
        public Nullable<int> COUNT_LOG { get; set; }
        public Nullable<System.Guid> UTILISATEUR { get; set; }
    }
}
