//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_MAILS_STATE
    {
        public int IDSTATE { get; set; }
        public Nullable<int> IDUSER { get; set; }
        public Nullable<int> LASTCOUNT { get; set; }
        public Nullable<System.DateTime> LASTRECEPT { get; set; }
    }
}
