//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.BACKOFFICE_GEST = new HashSet<BACKOFFICE_GEST>();
        }
    
        public Nullable<System.Guid> ID { get; set; }
        public int iduser { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string CRYPTEDPASS { get; set; }
        public Nullable<int> MASTER { get; set; }
        public Nullable<int> AGENCE { get; set; }
        public Nullable<bool> ADMIN { get; set; }
        public string CIVILITE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string LOGIN_MESSAGERIE { get; set; }
        public string MDP_MESSAGERIE { get; set; }
        public string NOM_RESEAU { get; set; }
        public Nullable<int> NIVEAU { get; set; }
        public string CLE { get; set; }
        public string DROITS_FICHIERS { get; set; }
        public string REPERTOIRE { get; set; }
        public string USER1 { get; set; }
        public string PASS1 { get; set; }
        public Nullable<bool> ACTIF { get; set; }
        public Nullable<int> TEMPLATE { get; set; }
        public Nullable<int> IDTEMPLATE { get; set; }
        public Nullable<bool> SU { get; set; }
        public string SESSIONID { get; set; }
        public Nullable<bool> ISCONNECTED { get; set; }
        public string SIGNATURE { get; set; }
        public Nullable<bool> CHOIX_SIGNATURE { get; set; }
        public Nullable<int> ESSAIS { get; set; }
        public Nullable<bool> COMPTE_BWALL { get; set; }
        public Nullable<bool> COMPTE_SUPPORT { get; set; }
        public Nullable<bool> COMPTE_GENERIQUE { get; set; }
        public Nullable<bool> GEST_PERSONNES { get; set; }
        public Nullable<bool> GEST_DATA { get; set; }
        public Nullable<bool> COMPTE_FREE { get; set; }
        public Nullable<int> QUESTION1 { get; set; }
        public string REPONSE1 { get; set; }
        public Nullable<int> QUESTION2 { get; set; }
        public string REPONSE2 { get; set; }
        public Nullable<int> QUESTION3 { get; set; }
        public string REPONSE3 { get; set; }
        public string DEFAULT_GEST_DATA { get; set; }
        public string TELEPHONE { get; set; }
        public string MOBILE { get; set; }
        public string FONCTION { get; set; }
        public Nullable<System.Guid> UTILISATEUR { get; set; }
        public string TOKENNC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BACKOFFICE_GEST> BACKOFFICE_GEST { get; set; }
    }
}
