//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCARDS
    {
        public int IDVCARD { get; set; }
        public string USERKEY { get; set; }
        public string VCARD { get; set; }
        public Nullable<System.DateTime> REV { get; set; }
        public string UID { get; set; }
    }
}
