//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsposePdfEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class VERSIONS
    {
        public int IDVERSION { get; set; }
        public string USERKEY { get; set; }
        public Nullable<int> TYPE_VERSION { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> DATE_VERSION { get; set; }
        public string HASHVERSION { get; set; }
        public string EMPLACEMENT { get; set; }
        public string HEURE_VERSION { get; set; }
    }
}
